/* ============================================================================
   E-02 EMPLOYER PROFILE — schema additions
   Run this against MANPOWER_HIRING_DB before using the new EF model.
   ============================================================================ */

-- 1) Admin-managed master list of business/industry categories -------------
CREATE TABLE BUSINESS_CATEGORY (
    BUSINESS_CATEGORY_ID   INT IDENTITY(1,1)      NOT NULL,
    CATEGORY_NAME           NVARCHAR(150)           NOT NULL,
    IS_ACTIVE_FL             BIT                     NOT NULL CONSTRAINT DF_BUSINESS_CATEGORY_ACTIVE_FL DEFAULT (1),

    CREATED_BY               NVARCHAR(100)           NOT NULL CONSTRAINT DF_BUSINESS_CATEGORY_CREATED_BY DEFAULT ('SYSTEM'),
    CREATED_TS               DATETIME2               NOT NULL CONSTRAINT DF_BUSINESS_CATEGORY_CREATED_TS DEFAULT (SYSUTCDATETIME()),
    CREATED_IP_ADDR          VARCHAR(45)              NULL,
    UPDATED_BY                NVARCHAR(100)           NULL,
    UPDATED_TS                DATETIME2               NULL,
    UPDATED_IP_ADDR           VARCHAR(45)              NULL,

    CONSTRAINT PK_BUSINESS_CATEGORY PRIMARY KEY (BUSINESS_CATEGORY_ID),
    CONSTRAINT UQ_BUSINESS_CATEGORY_NAME UNIQUE (CATEGORY_NAME)
);
GO

INSERT INTO BUSINESS_CATEGORY (CATEGORY_NAME, CREATED_BY) VALUES
('Restaurants', 'SYSTEM_SEED'),
('Hotels', 'SYSTEM_SEED'),
('Manufacturing', 'SYSTEM_SEED'),
('Pan India Retail / Malls', 'SYSTEM_SEED'),
('Events', 'SYSTEM_SEED'),
('Construction', 'SYSTEM_SEED'),
('Financial Services', 'SYSTEM_SEED'),
('Warehouses', 'SYSTEM_SEED'),
('Facility Management', 'SYSTEM_SEED'),
('Maintenance Services', 'SYSTEM_SEED'),
('Worker Insurance', 'SYSTEM_SEED'),
('Hospitals', 'SYSTEM_SEED'),
('Commercial Offices', 'SYSTEM_SEED'),
('Training Marketplace', 'SYSTEM_SEED');
GO

-- 2) New columns on EMPLOYER_PROFILE for Contact Person + business proof ---
ALTER TABLE EMPLOYER_PROFILE ADD
    CONTACT_PERSON_NAME                  NVARCHAR(150)   NULL,
    BUSINESS_CATEGORY_ID                  INT             NULL,
    BUSINESS_PROOF_TYPE_CD                 VARCHAR(20)     NULL,   -- 'GST' | 'GUMASTHA'
    BUSINESS_PROOF_NUMBER_TXT              VARCHAR(30)     NULL,
    BUSINESS_PROOF_ORIGINAL_FILE_NAME_TXT  NVARCHAR(255)   NULL,
    BUSINESS_PROOF_FILE_PATH_TXT           NVARCHAR(500)   NULL,
    BUSINESS_PROOF_REVIEW_STATUS_CD        VARCHAR(20)     NOT NULL
        CONSTRAINT DF_EMPLOYER_PROFILE_PROOF_REVIEW_STATUS_CD DEFAULT ('PENDING');
GO

ALTER TABLE EMPLOYER_PROFILE ADD CONSTRAINT FK_EMPLOYER_PROFILE_BUSINESS_CATEGORY
    FOREIGN KEY (BUSINESS_CATEGORY_ID) REFERENCES BUSINESS_CATEGORY(BUSINESS_CATEGORY_ID);
GO

ALTER TABLE EMPLOYER_PROFILE ADD CONSTRAINT CK_EMPLOYER_PROFILE_PROOF_TYPE_CD
    CHECK (BUSINESS_PROOF_TYPE_CD IS NULL OR BUSINESS_PROOF_TYPE_CD IN ('GST', 'GUMASTHA'));
GO

ALTER TABLE EMPLOYER_PROFILE ADD CONSTRAINT CK_EMPLOYER_PROFILE_PROOF_REVIEW_STATUS_CD
    CHECK (BUSINESS_PROOF_REVIEW_STATUS_CD IN ('PENDING', 'APPROVED', 'REJECTED'));
GO

CREATE INDEX IX_EMPLOYER_PROFILE_BUSINESS_CATEGORY_ID ON EMPLOYER_PROFILE(BUSINESS_CATEGORY_ID);
GO
