/* ============================================================================
   09. EMPLOYER-GENERATED OTP + JOB_STARTED STATUS
   ----------------------------------------------------------------------------
   Reverses OTP direction: the EMPLOYER now generates OTPs (not the employee).
   Two OTP "types" are introduced per job application:
     - JOB_START    : generated by employer when the Kaarigar reaches the
                       job site; Kaarigar enters it to confirm arrival/start.
     - SATISFACTION : generated by employer once the job is finished;
                       Kaarigar enters it to confirm satisfactory completion.

   JOB_APPLICATION.STATUS_CD gains a new value, JOB_STARTED, sitting between
   EMPLOYER_CONTACTED and COMPLETED. OTP_VERIFIED is no longer used going
   forward (existing rows, if any, are migrated to JOB_STARTED).
   ============================================================================ */

-- 1. OTP_RECORD: track which employer generated it and what type of OTP it is.
ALTER TABLE OTP_RECORD ADD OTP_TYPE_CD VARCHAR(20) NOT NULL CONSTRAINT DF_OTP_RECORD_TYPE_CD DEFAULT ('JOB_START');
GO

ALTER TABLE OTP_RECORD ADD EMPLOYER_USER_ACCOUNT_ID INT NULL;
GO

ALTER TABLE OTP_RECORD ADD CONSTRAINT FK_OTP_RECORD_EMPLOYER
    FOREIGN KEY (EMPLOYER_USER_ACCOUNT_ID) REFERENCES USER_ACCOUNT(USER_ACCOUNT_ID);
GO

ALTER TABLE OTP_RECORD ADD CONSTRAINT CK_OTP_RECORD_TYPE_CD
    CHECK (OTP_TYPE_CD IN ('JOB_START', 'SATISFACTION'));
GO

-- 2. JOB_APPLICATION: allow the new JOB_STARTED status.
ALTER TABLE JOB_APPLICATION DROP CONSTRAINT CK_JOB_APPLICATION_STATUS_CD;
GO

-- Migrate any existing OTP_VERIFIED rows forward to the new status name.
UPDATE JOB_APPLICATION SET STATUS_CD = 'JOB_STARTED' WHERE STATUS_CD = 'OTP_VERIFIED';
GO

ALTER TABLE JOB_APPLICATION ADD CONSTRAINT CK_JOB_APPLICATION_STATUS_CD
    CHECK (STATUS_CD IN ('PENDING','EMPLOYER_VIEWED','EMPLOYER_CONTACTED','JOB_STARTED','COMPLETED'));
GO
