/* ============================================================================
   11. LEARNING VIDEO MODULE
   ============================================================================ */
CREATE TABLE LEARNING_VIDEO (
    LEARNING_VIDEO_ID   INT IDENTITY(1,1) NOT NULL,
    SKILL_ID             INT               NOT NULL,
    TITLE                  NVARCHAR(200)     NOT NULL,
    DESCRIPTION_TXT         NVARCHAR(1000)    NULL,
    VIDEO_URL                 NVARCHAR(400)     NOT NULL,
    IS_ACTIVE_FL              BIT               NOT NULL CONSTRAINT DF_LEARNING_VIDEO_IS_ACTIVE_FL DEFAULT (1),

    CREATED_BY           NVARCHAR(100)     NOT NULL CONSTRAINT DF_LEARNING_VIDEO_CREATED_BY DEFAULT ('SYSTEM'),
    CREATED_TS            DATETIME2         NOT NULL CONSTRAINT DF_LEARNING_VIDEO_CREATED_TS DEFAULT (SYSUTCDATETIME()),
    UPDATED_BY             NVARCHAR(100)     NULL,
    UPDATED_TS              DATETIME2         NULL,

    CONSTRAINT PK_LEARNING_VIDEO PRIMARY KEY (LEARNING_VIDEO_ID),
    CONSTRAINT FK_LEARNING_VIDEO_SKILL FOREIGN KEY (SKILL_ID) REFERENCES SKILL(SKILL_ID)
);
GO

CREATE INDEX IX_LEARNING_VIDEO_SKILL ON LEARNING_VIDEO(SKILL_ID, IS_ACTIVE_FL);
GO
