/* ============================================================================
   14. EMPLOYER CANCEL APPLICANT (before job start) WORKFLOW
   ============================================================================ */

ALTER TABLE JOB_APPLICATION DROP CONSTRAINT CK_JOB_APPLICATION_STATUS_CD;
GO
ALTER TABLE JOB_APPLICATION ADD CONSTRAINT CK_JOB_APPLICATION_STATUS_CD
    CHECK (STATUS_CD IN (
        'PENDING','EMPLOYER_VIEWED','EMPLOYER_CONTACTED','JOB_STARTED','COMPLETED','CANCELLED'
    ));
GO

ALTER TABLE JOB_APPLICATION ADD CANCEL_REASON_CD NVARCHAR(30) NULL;
GO
ALTER TABLE JOB_APPLICATION ADD CANCEL_REASON_TXT NVARCHAR(500) NULL;
GO
ALTER TABLE JOB_APPLICATION ADD CANCELLED_TS DATETIME2 NULL;
GO
