namespace Kaarigar.Models;

/// <summary>
/// Screen E-05: Job Detail & Applicants.
/// Full job details at the top + the list of employees who expressed interest.
/// </summary>
public class JobDetailViewModel
{
    public int JobPostId { get; set; }
    public string JobTitle { get; set; } = string.Empty;
    public string? DescriptionTxt { get; set; }
    public int RequiredWorkerNbr { get; set; }
    public decimal? HourlyWageAmt { get; set; }
    public DateTime? StartDt { get; set; }
    public int? DurationHourNbr { get; set; }
    public TimeSpan? StartTime { get; set; }

    /// <summary>Calculated: StartDt + StartTime.</summary>
    public DateTime? StartDateTime { get; set; }

    /// <summary>Calculated: StartDateTime + DurationHourNbr hours.</summary>
    public DateTime? EndDateTime { get; set; }
    public string? LocationAddressTxt { get; set; }
    public string? ContactNbr { get; set; }
    public string StatusCd { get; set; } = "ACTIVE";
    public List<string> RequiredSkillNames { get; set; } = new();

    public List<ApplicantListItemViewModel> Applicants { get; set; } = new();
}

/// <summary>
/// One row in E-05's applicant list: Name, Skills, Location,
/// Distance from Job Site, and the current contact/verification state.
/// </summary>
public class ApplicantListItemViewModel
{
    public int JobApplicationId { get; set; }
    public int EmployeeUserAccountId { get; set; }
    public string Name { get; set; } = string.Empty;
    public List<string> SkillNames { get; set; } = new();
    public string? Location { get; set; }
    public double? DistanceKm { get; set; }

    /// <summary>PENDING | EMPLOYER_VIEWED | EMPLOYER_CONTACTED | JOB_STARTED | COMPLETED</summary>
    public string StatusCd { get; set; } = "PENDING";
    public DateTime AppliedTs { get; set; }

    /// <summary>Populated only after "Contact Employee" has been used, so the phone can be shown.</summary>
    public string? RevealedContactNbr { get; set; }

    /// <summary>Set while a Job Starting OTP generated by the employer is still live (unused &amp; unexpired) for this Kaarigar.</summary>
    public string? ActiveJobStartOtpCd { get; set; }
    public DateTime? ActiveJobStartOtpExpiresTs { get; set; }

    /// <summary>Set while a Satisfaction OTP generated by the employer is still live (unused &amp; unexpired) for this Kaarigar.</summary>
    public string? ActiveSatisfactionOtpCd { get; set; }
    public DateTime? ActiveSatisfactionOtpExpiresTs { get; set; }

    /// <summary>Show the "Generate Job Starting OTP" button (no live code showing, job not started/completed yet).</summary>
    public bool CanGenerateJobStartOtp => ActiveJobStartOtpCd == null && StatusCd is "PENDING" or "EMPLOYER_VIEWED" or "EMPLOYER_CONTACTED";

    /// <summary>Show the "Generate Satisfaction OTP" button (no live code showing, job already started but not completed).</summary>
    public bool CanGenerateSatisfactionOtp => ActiveSatisfactionOtpCd == null && StatusCd == "JOB_STARTED";

    /// <summary>Already-submitted rating for this application, if any.</summary>
    public byte? RatingNbr { get; set; }

    /// <summary>Show the rating form — job completed and not yet rated.</summary>
    public bool CanRate => StatusCd == "COMPLETED" && RatingNbr == null;
}

/// <summary>
/// Screen E-06: Employee Profile View (read-only).
/// Name, Skills, Location, Experience Note (if any) + a Verify OTP action.
/// </summary>
public class ApplicantProfileViewModel
{
    public int JobApplicationId { get; set; }
    public int JobPostId { get; set; }
    public string JobTitle { get; set; } = string.Empty;

    public int EmployeeUserAccountId { get; set; }
    public string Name { get; set; } = string.Empty;
    public List<string> SkillNames { get; set; } = new();
    public string? Location { get; set; }
    public string? ExperienceNoteTxt { get; set; }

    public string StatusCd { get; set; } = "PENDING";
}
